parallel-consumer-core/pom.xml, parallel-consumer-vertx/pom.xml, pom.xml
=> Fix plugin versions fix surefire bug 

.github/CODEOWNERS, .github/workflows/maven.yml, parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/ParallelEoSStreamProcessor.java, parallel-consumer-core/src/test/java/io/confluent/parallelconsumer/ParallelEoSStreamProcessorTest.java
=> Fixes #101: NPE on auto commit check

.idea/runConfigurations/All_core_unit_tests.xml, parallel-consumer-core/src/test-integration/java/io/confluent/parallelconsumer/integrationTests/DbTest.java, parallel-consumer-core/src/test-integration/java/io/confluent/parallelconsumer/integrationTests/KafkaSanityTests.java, parallel-consumer-core/src/test-integration/java/io/confluent/parallelconsumer/integrationTests/MultiInstanceRebalanceTest.java, parallel-consumer-core/src/test-integration/java/io/confluent/parallelconsumer/integrationTests/OffsetCommittingSanityTest.java, parallel-consumer-core/src/test/java/io/confluent/csid/utils/LongPollingMockConsumer.java, parallel-consumer-core/src/test/java/io/confluent/parallelconsumer/OffsetEncodingBackPressureTest.java, parallel-consumer-core/src/test/java/io/confluent/parallelconsumer/OffsetEncodingTests.java, parallel-consumer-core/src/test/resources/junit-platform.properties, parallel-consumer-vertx/src/test-integration/java/io/confluent/parallelconsumer/vertx/integrationTests/VertxConcurrencyIT.java, pom.xml
=> Switch to parallel test runs

pom.xml
Experiencing some failures in Jenkins environment.
=> tests: Turn off parallel tests in CI profile

parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/offsets/OffsetMapCodecManager.java, parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/state/PartitionMonitor.java, parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/state/PartitionState.java, parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/state/ShardManager.java, parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/state/WorkManager.java, parallel-consumer-core/src/test-integration/java/io/confluent/parallelconsumer/integrationTests/CloseAndOpenOffsetTest.java, parallel-consumer-core/src/test-integration/java/io/confluent/parallelconsumer/integrationTests/TransactionAndCommitModeTest.java, parallel-consumer-core/src/test-integration/java/io/confluent/parallelconsumer/integrationTests/VeryLargeMessageVolumeTest.java, parallel-consumer-core/src/test/java/io/confluent/parallelconsumer/ParallelEoSStreamProcessorTest.java, parallel-consumer-core/src/test/java/io/confluent/parallelconsumer/ParallelEoSStreamProcessorTestBase.java, parallel-consumer-core/src/test/java/io/confluent/parallelconsumer/offsets/OffsetEncodingBackPressureTest.java, parallel-consumer-core/src/test/java/io/confluent/parallelconsumer/offsets/WorkManagerOffsetMapCodecManagerTest.java, parallel-consumer-core/src/test/java/io/confluent/parallelconsumer/state/WorkManagerTest.java, parallel-consumer-vertx/src/main/java/io/confluent/parallelconsumer/vertx/VertxParallelEoSStreamProcessor.java
General clean-up, renames, simple refactors etc...
=> refactor: todos left over from large refactor

parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/ParallelConsumerOptions.java, parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/ParallelEoSStreamProcessor.java, parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/internal/BrokerPollSystem.java
As far as I looked I only found two places where ExecutorService or ThreadFactory is being used.
=> Make parallel consumer java ee compliant

.github/workflows/maven.yml, parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/ParallelEoSStreamProcessor.java, parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/internal/ConsumerManager.java, parallel-consumer-examples/parallel-consumer-example-vertx/src/main/java/io/confluent/parallelconsumer/examples/vertx/VertxApp.java, pom.xml
Fixes #60 - upgrade AK to 2.7.0.
Adds 2.7.0 as a stable build.
=> Major: Upgrade to AK 2.7.0

parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/state/WorkManager.java
Hi,
We are using "WARN" log level and switching to "INFO"/"DEBUG" level will lead to a lot of noise - though "Warning: {} records in the queue have been waiting longer than {}" is important enough but lacks details to troubleshoot the potential problem.
Shall at least topic names be added to that log message?
=> show record topic in slow-work warning message

README.adoc, parallel-consumer-core/src/test/java/io/confluent/csid/utils/CollectionUtils.java, parallel-consumer-core/src/test/java/io/confluent/parallelconsumer/model/CommitHistory.java, parallel-consumer-core/src/test/java/io/confluent/parallelconsumer/truth/CommitHistorySubject.java
Don't know how this made it through CI.
=> fix: Out of bounds for empty collections

parallel-consumer-core/pom.xml, parallel-consumer-core/src/main/java/io/confluent/csid/utils/MathUtils.java, parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/internal/AbstractParallelEoSStreamProcessor.java, parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/internal/DynamicLoadFactor.java, parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/internal/ExternalEngine.java, parallel-consumer-core/src/test-integration/java/io/confluent/parallelconsumer/integrationTests/BrokerIntegrationTest.java, parallel-consumer-core/src/test-integration/java/io/confluent/parallelconsumer/integrationTests/LargeVolumeInMemoryTests.java, parallel-consumer-core/src/test/java/io/confluent/csid/utils/KafkaTestUtils.java, parallel-consumer-core/src/test/java/io/confluent/csid/utils/LatchTestUtils.java, parallel-consumer-core/src/test/java/io/confluent/csid/utils/ThreadUtils.java, parallel-consumer-core/src/test/java/io/confluent/parallelconsumer/AbstractParallelEoSStreamProcessorTestBase.java, parallel-consumer-core/src/test/java/io/confluent/parallelconsumer/offsets/OffsetEncodingBackPressureTest.java, parallel-consumer-reactor/src/test/java/io/confluent/parallelconsumer/reactor/ReactorPCTest.java, parallel-consumer-vertx/pom.xml, parallel-consumer-vertx/src/main/java/io/confluent/parallelconsumer/vertx/VertxParallelEoSStreamProcessor.java, parallel-consumer-vertx/src/test-integration/java/io/confluent/parallelconsumer/vertx/integrationTests/VertxConcurrencyIT.java
=> Migrate vert.x module to fixed concurrency system

pom.xml
Updated enforcer plugin configuration to exclude java 14.
=> Updated enforcer plugin configuration to exclude java 14

parallel-consumer-core/pom.xml, parallel-consumer-examples/parallel-consumer-example-core/pom.xml, parallel-consumer-examples/parallel-consumer-example-reactor/pom.xml, parallel-consumer-examples/parallel-consumer-example-streams/pom.xml, parallel-consumer-examples/parallel-consumer-example-vertx/pom.xml, parallel-consumer-examples/pom.xml, parallel-consumer-reactor/pom.xml, parallel-consumer-vertx/pom.xml, pom.xml
Preparation for the 0.4 release - some things need fixing.
Blocked by https://github.com/confluentinc/parallel-consumer/pull/157
=> Release 0.4.0.0

.idea/runConfigurations/asciidoc_template_build.xml, .idea/runConfigurations/license_format.xml, README.adoc, parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/ParallelConsumerOptions.java, parallel-consumer-examples/parallel-consumer-example-core/src/main/java/io/confluent/parallelconsumer/examples/core/CoreApp.java, src/docs/README.adoc
=> docs: Retry documentation

parallel-consumer-core/pom.xml, parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/internal/ConsumerOffsetCommitter.java, parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/offsets/ByteBufferEncoder.java, parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/offsets/EncodedOffsetPair.java, parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/offsets/OffsetEncoder.java, parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/offsets/OffsetEncoding.java, parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/offsets/RunLengthEncoder.java, parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/state/WorkContainer.java, parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/state/WorkManager.java, parallel-consumer-core/src/test-integration/java/io/confluent/parallelconsumer/integrationTests/DbTest.java, parallel-consumer-core/src/test-integration/java/io/confluent/parallelconsumer/integrationTests/MultiInstanceRebalanceTest.java, parallel-consumer-core/src/test-integration/java/io/confluent/parallelconsumer/integrationTests/TransactionAndCommitModeTest.java, parallel-consumer-core/src/test/java/io/confluent/csid/utils/InstanceUtils.java, parallel-consumer-core/src/test/java/io/confluent/csid/utils/MyRunListener.java, parallel-consumer-core/src/test/java/io/confluent/csid/utils/PodamUtils.java, parallel-consumer-core/src/test/java/io/confluent/parallelconsumer/state/ModelUtils.java, parallel-consumer-core/src/test/java/io/confluent/parallelconsumer/state/PartitionStateTest.java, parallel-consumer-core/src/test/java/io/confluent/parallelconsumer/state/WorkContainerTest.java, parallel-consumer-core/src/test/java/io/confluent/parallelconsumer/state/WorkManagerTest.java, parallel-consumer-core/src/test/java/io/confluent/parallelconsumer/truth/TruthGeneratorTests.java, parallel-consumer-examples/parallel-consumer-example-core/pom.xml, pom.xml
=> #247: Adopt Truth-Generator

Jenkinsfile, README.adoc, parallel-consumer-core/src/main/java/io/confluent/csid/utils/MathUtils.java, parallel-consumer-core/src/test/java/io/confluent/parallelconsumer/truth/TruthGeneratorTests.java, parallel-consumer-reactor/pom.xml, parallel-consumer-vertx/pom.xml, src/docs/README.adoc
https://oss.sonatype.org/content/repositories/snapshots/io/confluent/parallelconsumer/
=> build: Deploy SNAPSHOTS to maven central snaphots repo

parallel-consumer-core/src/test-integration/java/io/confluent/parallelconsumer/integrationTests/CloseAndOpenOffsetTest.java, parallel-consumer-core/src/test-integration/java/io/confluent/parallelconsumer/integrationTests/LargeVolumeInMemoryTests.java, parallel-consumer-core/src/test/java/io/confluent/csid/utils/TrimListRepresentation.java, parallel-consumer-core/src/test/java/io/confluent/parallelconsumer/state/WorkManagerTest.java
- Swap for direct dependencies
- Fix some other stuff
=> fix: Remove shaded imports

.github/workflows/maven.yml, Jenkinsfile, parallel-consumer-core/src/test-integration/java/io/confluent/parallelconsumer/integrationTests/DbTest.java, pom.xml, src/docs/README.adoc
=> fixes: #225 Support Java 17

parallel-consumer-reactor/pom.xml, pom.xml
=> build(deps): dependabot bump Mockito, Surefire, Reactor, AssertJ, Release (#342)

service.yml
=> Build: Add PC to Semaphore

parallel-consumer-core/pom.xml, parallel-consumer-reactor/pom.xml, pom.xml
prod: zstd, reactor,
dev: podam, progressbar,  postgresql
maven-plugins: versions, help
=> build(deps):  prod: zstd, reactor, dev: podam, progressbar, postgresql maven-plugins: versions, help

pom.xml
=> build(deps): bump jabel from 0.4.2 to 1.0.0 (Java 19 support)

parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/state/PartitionState.java, parallel-consumer-core/src/test-integration/java/io/confluent/parallelconsumer/integrationTests/state/PartitionStateCommittedOffsetIT.java, parallel-consumer-core/src/test/java/io/confluent/parallelconsumer/state/PartitionStateCommittedOffsetTest.java, pom.xml
=> refactor #409: Clarify truncation code

parallel-consumer-core/src/main/java/io/confluent/csid/utils/BackportUtils.java, parallel-consumer-core/src/main/java/io/confluent/csid/utils/LoopingResumingIterator.java, parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/state/ShardManager.java, parallel-consumer-core/src/test/java/io/confluent/csid/utils/LoopingResumingIteratorTest.java, parallel-consumer-core/src/test/resources/logback-test.xml
fix for java.util.NoSuchElementException: #hasNext() returned true, but there are no more entries that haven't been iterated.
Related:
- #200
=> fixes: NoSuchElementException in LoopingResumingIterator

parallel-consumer-core/pom.xml, parallel-consumer-reactor/pom.xml, pom.xml
=> build(deps): wiremock, mvn-release, reactor, podam, postgresql, junit-pioneer

parallel-consumer-core/src/test/java/io/confluent/parallelconsumer/ParallelEoSStreamProcessorTest.java, parallel-consumer-core/src/test/java/io/confluent/parallelconsumer/offsets/WorkManagerOffsetMapCodecManagerTest.java, parallel-consumer-core/src/test/java/io/confluent/parallelconsumer/state/WorkManagerTest.java
Migrated to separate branch - astubbs/refactor/empty-tests
See:
- #494 
- #496
=> minor: tests: Removes empty/not implemented tests

parallel-consumer-vertx/pom.xml, pom.xml
=> build(deps): vertx, maven-dependency, testcontainers, logback, mockito

parallel-consumer-core/src/main/java/io/confluent/csid/utils/Java8StreamUtils.java, parallel-consumer-core/src/test/java/io/confluent/parallelconsumer/AbstractParallelEoSStreamProcessorTestBase.java, parallel-consumer-core/src/test/java/io/confluent/parallelconsumer/JStreamParallelEoSStreamProcessorTest.java, parallel-consumer-core/src/test/java/io/confluent/parallelconsumer/ParallelEoSStreamProcessorTestBase.java
=> minor: JStream review / generics fixes

parallel-consumer-reactor/pom.xml, parallel-consumer-vertx/pom.xml, pom.xml
=> build(deps): bump vertx.version, maven-install, slf4j-api, reactor-core, versions-maven-plugin

parallel-consumer-core/src/main/java/io/confluent/csid/utils/BackportUtils.java, parallel-consumer-core/src/main/java/io/confluent/csid/utils/KafkaUtils.java, parallel-consumer-core/src/main/java/io/confluent/csid/utils/LoopingResumingIterator.java, parallel-consumer-core/src/main/java/io/confluent/csid/utils/StringUtils.java
Add missing `@UtilityClass` to utils
=> Add missing @UtilityClass to utils class

Jenkinsfile, README.adoc, parallel-consumer-python-tests/pom.xml, parallel-consumer-python/README.adoc, parallel-consumer-python/bin/install-and-run-tests.sh, parallel-consumer-python/bin/publish.sh, parallel-consumer-python/examples/kafka.py, parallel-consumer-python/examples/normal_consumer.py, parallel-consumer-python/examples/parallel_consumption.py, parallel-consumer-python/pyallel_consumer/__init__.py, parallel-consumer-python/setup.py, parallel-consumer-python/tests/__init__.py, parallel-consumer-python/tests/kafka_utils.py, parallel-consumer-python/tests/load/conftest.py, parallel-consumer-python/tests/load/test_python_client.py
Publish built python package to [Confluent's PyPi account](https://pypi.org/user/confluent/), making it easily and readily installable
=> Automatically Publish Python Package to PyPi

README.adoc, parallel-consumer-core/pom.xml, parallel-consumer-examples/parallel-consumer-example-core/pom.xml, parallel-consumer-examples/parallel-consumer-example-reactor/pom.xml, parallel-consumer-examples/parallel-consumer-example-streams/pom.xml, parallel-consumer-examples/parallel-consumer-example-vertx/pom.xml, parallel-consumer-examples/pom.xml, parallel-consumer-reactor/pom.xml, parallel-consumer-vertx/pom.xml, pom.xml
Updated license headers in POMs and regenerated the readme to include updated changelog - prep for release.
=> cleanup: updated license in POMs, regenerated readme

.mvn/wrapper/maven-wrapper.properties, CHANGELOG.adoc, Jenkinsfile, mvnw, mvnw.cmd, parallel-consumer-vertx/pom.xml, pom.xml
Updates dependencies, adds maven wrapper, jenkins to use mavenwrapper if possible.
=> PL-211: Update dependencies from dependabot, Add mvnw, use mvnw in jenkins

parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/internal/AbstractParallelEoSStreamProcessor.java, parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/internal/BrokerPollSystem.java
just add instance id into thread name, this would help debug
=> add instance id into thread name

parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/internal/BrokerPollSystem.java, parallel-consumer-core/src/test-integration/java/io/confluent/parallelconsumer/integrationTests/DrainCloseTest.java
Fix for pausing subscriptions when DRAIN mode is active
JIRA - https://confluentinc.atlassian.net/browse/PL-175
=> Pl 175 DRAIN mode fix

CHANGELOG.adoc, README.adoc, parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/state/PartitionState.java, parallel-consumer-core/src/test/java/io/confluent/parallelconsumer/state/PartitionStateCommittedOffsetTest.java
Fix for race condition in partition state clean/dirty tracking - see #664
=> Fix for race condition in partition state clean/dirty tracking

service.yml
enable git switch for semaphore job generation.
=> Enable semaphore

.gitignore, Makefile, pom.xml, service.yml, sonar-project.properties
This is a routine update from cc-service-bot based on the service.yml in your repo. This PR
should be approved and merged as soon as CI passes.
=> chore: update repo by service bot

.semaphore/semaphore.yml, parallel-consumer-reactor/src/main/java/io/confluent/parallelconsumer/reactor/ReactorProcessor.java
Setting up semaphore job to replace jenkins
=> update semaphore to unshallow git for license check to work correctly

README.adoc, src/docs/README_TEMPLATE.adoc
Moved Readme corrections raised in #735 into Readme template file.
=> docs: readme - move changes in #735 into template

.semaphore/initgpg.sh, .semaphore/project.yml, .semaphore/project_public.yml, .semaphore/publish_to_maven.yml, .semaphore/release.yml, .semaphore/semaphore_public.yml
Added release pipeline to semaphore configs.
=> add release pipeline for semaphore

service.yml
Fix tasks block in service.yml - has to be inside semaphore block.
=> Move tasks block into semaphore block in service.yml

parallel-consumer-core/src/test/java/io/confluent/parallelconsumer/ParallelEoSStreamProcessorTest.java
add wait cycles to flaky test - queuedMessagesNotProcessedOrCommittedIfSubmittedDuringShutdown
=> Add wait cycles in a test to help de-flake it.

parallel-consumer-reactor/src/main/java/io/confluent/parallelconsumer/reactor/ReactorProcessor.java, parallel-consumer-reactor/src/test/java/io/confluent/parallelconsumer/reactor/ReactorPCTest.java
Merge of PR (#794)
This contribution fixes the issue described here https://github.com/confluentinc/parallel-consumer/issues/793
=> Run user defined react function in provided scheduler

CHANGELOG.adoc, README.adoc, parallel-consumer-reactor/src/main/java/io/confluent/parallelconsumer/reactor/ReactorProcessor.java, parallel-consumer-reactor/src/test/java/io/confluent/parallelconsumer/reactor/ReactorPCTest.java
Merge of PR #794 by [yevheniisemenov](https://github.com/yevheniisemenov)
Fixes the issue described here #793
=> Run used-defined function in provided scheduler rather than in pc-pool thread

.semaphore/release.yml, pom.xml
=> push changes on release prepare steps

.semaphore/release.yml
=> dont do release:perform in release task - its part of deploy

.semaphore/publish_to_maven.yml, .semaphore/update_maven_settings.py, parallel-consumer-core/pom.xml, parallel-consumer-examples/parallel-consumer-example-core/pom.xml, parallel-consumer-examples/parallel-consumer-example-metrics/pom.xml, parallel-consumer-examples/parallel-consumer-example-reactor/pom.xml, parallel-consumer-examples/parallel-consumer-example-streams/pom.xml, parallel-consumer-examples/parallel-consumer-example-vertx/pom.xml, parallel-consumer-examples/pom.xml, parallel-consumer-reactor/pom.xml, parallel-consumer-vertx/pom.xml, pom.xml
Backout release prep commits for 0.5.3.0. 
Add changes to semaphore publish script to handle injection of ossrh staging repo.
=> Backout release add ossrh handling

README.adoc
=> Update README for release

RELEASE.adoc
updates to release process steps in RELEASE.md based on changes in how its done now.
=> docs: updated release instructions

pom.xml
=> Update maven site plugin versionm15

README.adoc, src/docs/README_TEMPLATE.adoc
=> chore: Fix typo in README
