confluentinc/parallel-consumer

parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/ConsumerManager.java
parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/OffsetSimultaneousEncoder.java
parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/ParallelEoSStreamProcessor.java
parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/WorkContainer.java
parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/WorkManager.java
parallel-consumer-core/src/test-integration/java/io/confluent/parallelconsumer/integrationTests/VeryLargeMessageVolumeTest.java
parallel-consumer-core/src/test/java/io/confluent/csid/utils/TrimListRepresentation.java

Fixes #35 RuntimeException when running with very high options in 0.2.0.0 (Bitset too long to encode) #35
Was left over from old code, before WorkManager#maybeStripOffsetPayload was added

fix: Remove legacy offset bitmap length test

---

CHANGELOG.adoc
parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/BitsetEncoder.java
parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/EncodedOffsetPair.java
parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/OffsetBitSet.java
parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/OffsetEncoder.java
parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/OffsetEncoding.java
parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/OffsetMapCodecManager.java
parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/OffsetRunLength.java
parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/OffsetSimultaneousEncoder.java
parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/RunLengthEncoder.java
parallel-consumer-core/src/test/java/io/confluent/parallelconsumer/OffsetEncodingTests.java
parallel-consumer-core/src/test/resources/junit-platform.properties
parallel-consumer-core/src/test/resources/logback-test.xml

Fixes #37 Support BitSet and RunLength encoding lengths longer than Short.MAX_VALUE enhancement

feature: Large bitset and run-length encodings

---

parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/OffsetMapCodecManager.java
parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/WorkManager.java
parallel-consumer-core/src/test-integration/java/io/confluent/parallelconsumer/integrationTests/OffsetCommittingSanityTest.java
parallel-consumer-core/src/test/java/io/confluent/parallelconsumer/ParallelEoSStreamProcessorTest.java

Fixes #62 - the off by one issue would cause first message to be skipped in some situations

Fix for Bug 62 skip record on restart - off by one one?

---

parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/ParallelEoSStreamProcessor.java

Have some cases where it's natural to not produce any records, so reducing the log-level for this situation.

Reduce log-level if no results are returned from user-function

---

Jenkinsfile

Use Confluent's new signing key.

Use 8B1DA6120C2BF624 GPG Key For Signing

---

parallel-consumer-core/src/test-integration/java/io/confluent/parallelconsumer/integrationTests/MultiInstanceHighVolumeTest.java
parallel-consumer-core/src/test-integration/java/io/confluent/parallelconsumer/integrationTests/MultiInstanceRebalanceTest.java
parallel-consumer-core/src/test-integration/java/io/confluent/parallelconsumer/integrationTests/OffsetCommittingSanityTest.java
parallel-consumer-core/src/test-integration/java/io/confluent/parallelconsumer/integrationTests/TransactionAndCommitModeTest.java
parallel-consumer-core/src/test-integration/java/io/confluent/parallelconsumer/integrationTests/VeryLargeMessageVolumeTest.java
parallel-consumer-core/src/test/java/io/confluent/csid/utils/LongPollingMockConsumer.java
parallel-consumer-core/src/test/java/io/confluent/parallelconsumer/OffsetEncodingBackPressureTest.java
parallel-consumer-core/src/test/resources/junit-platform.properties
pom.xml

See https://github.com/awaitility/awaitility/pull/193
Enables awaitility to fail much faster if the PC has died for some reason, causing no progress to be made, having to wait for the full Awaitility timeout to expire.

Upgrade to Awaitility fail fast feature now that it's merged and released

---

parallel-consumer-core/src/test/java/io/confluent/parallelconsumer/offsets/OffsetEncodingBackPressureTest.java
parallel-consumer-vertx/src/main/java/io/confluent/parallelconsumer/vertx/VertxParallelEoSStreamProcessor.java
parallel-consumer-vertx/src/main/java/io/confluent/parallelconsumer/vertx/VertxParallelStreamProcessor.java
parallel-consumer-vertx/src/test-integration/java/io/confluent/parallelconsumer/vertx/integrationTests/VertxConcurrencyIT.java
parallel-consumer-vertx/src/test/java/io/confluent/parallelconsumer/vertx/VertxTest.java
parallel-consumer-vertx/src/test/resources/logback-test.xml

Implements #93 - Generic Vert.x future and Java CompletableFuture  support

---

src/docs/README.adoc

Updated Readme - added note about maven compile target failure due to a test-jar dependency resolution bug.

Updated Readme - added note about maven compile target failure

---

parallel-consumer-core/src/test-integration/java/io/confluent/parallelconsumer/integrationTests/BrokerIntegrationTest.java
parallel-consumer-core/src/test-integration/java/io/confluent/parallelconsumer/integrationTests/CloseAndOpenOffsetTest.java
parallel-consumer-core/src/test-integration/java/io/confluent/parallelconsumer/integrationTests/KafkaSanityTests.java
parallel-consumer-core/src/test-integration/java/io/confluent/parallelconsumer/integrationTests/LoadTest.java
parallel-consumer-core/src/test-integration/java/io/confluent/parallelconsumer/integrationTests/TransactionAndCommitModeTest.java
parallel-consumer-core/src/test-integration/java/io/confluent/parallelconsumer/integrationTests/utils/KafkaClientUtils.java
parallel-consumer-examples/parallel-consumer-example-streams/src/test/java/io/confluent/parallelconsumer/examples/streams/StreamsAppTest.java
pom.xml

Cleans up warnings in logs of ignored properties.

refactor: Separate producer and consumer props

---

README.adoc
pom.xml

Was blocked by dependably upgrades:

build: Crank up Enforcer and turn on ossindex audit

---

.idea/runConfigurations/asciidoc_template_build.xml
README.adoc
pom.xml
src/docs/README_TEMPLATE.adoc

Blocked by: 
- https://github.com/whelk-io/asciidoc-template-maven-plugin/pull/119

docs: Correctly render includes when editing README template

---

README.adoc
pom.xml

- CVE-2020-8908: Files::createTempDir local information disclosure vulnerability #4011
- Only used transitively from tests, and is a deprecated function
- https://github.com/google/guava/issues/4011
Description...

build: OSS Index scan change to warn only and exclude Guava CVE-2020-8908 as it's WONT_FIX

---

pom.xml

From parent pom.xml, mockito dependency is not scoped as test.
https://github.com/confluentinc/parallel-consumer/issues/375

fixes #375: Mockito dependency should be test scoped

---

CHANGELOG.adoc
README.adoc
parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/state/PartitionState.java

In busy situations, there is a race condition in PartitionState due to it being edited by the Controller, and read by the BrokerPoller.
Because the check and subsequent read of the incompleteOffsets collection are two different operations, it can initially appear as though it has elements, but when we try to retrieve an element, it can then be empty, which throws a NoSuchElementException.
Thanks to a very elegant fix suggested by @shaileshkulkarni, we can combine the check and retrieval by using the thread safe #ceiling method, which can either returns the #first element, or null if empty.
This is as opposed to the more brute force solution which would require using locks.
This, among other things, will be made redundant once #200 (a shared nothing architecture) is merged.
Description...

fixes #419 NoSuchElementException during race condition in PartitionState

---

parallel-consumer-core/pom.xml
parallel-consumer-examples/parallel-consumer-example-reactor/pom.xml
parallel-consumer-examples/parallel-consumer-example-vertx/pom.xml
parallel-consumer-vertx/pom.xml
pom.xml

- Fix Slf4j setup by switching away from and bumping Wiremock fat dependency (slf4j/logback collisions)
- Upgrades Wiremock from 2.33.2 to 2.34.0

build(deps-dev): Fix Slf4j setup caused by shaded Wiremock dep (slf4j/logback collisions)

---

service.yml

Disabling semaphore for cc-service-bot since the repo does not use semaphore (and shouldn't since it is public).

Update service.yml - disable semaphore

---

parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/offsets/OffsetBitSet.java
parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/offsets/OffsetMapCodecManager.java
parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/offsets/OffsetRunLength.java
parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/state/PartitionState.java
parallel-consumer-core/src/test/java/io/confluent/parallelconsumer/state/PartitionStateCommittedOffsetTest.java

Two natures of SortedSet are used - contains() for fast lookup, and potential traversal in order (which there isn't atm). This change ensures that any potential traversals will always occur in Offset order. Otherwise, simply Set has no traversal order guarantees - which has been an issue in the past.
- #439

refactor: SortedSet's all the way down (Set->SortedSet)

---

CHANGELOG.adoc
README.adoc
RELEASE.adoc
parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/internal/AbstractParallelEoSStreamProcessor.java
parallel-consumer-core/src/test-integration/java/io/confluent/parallelconsumer/integrationTests/CustomConsumersTest.java
parallel-consumer-core/src/test-integration/java/io/confluent/parallelconsumer/integrationTests/utils/KafkaClientUtils.java
parallel-consumer-core/src/test/java/io/confluent/parallelconsumer/ParallelEoSStreamProcessorTest.java

fixes: #195 NoSuchFieldException when using consumer inherited from KafkaConsumer

---

parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/state/PartitionState.java

Adding partition to warn Truncating log
Description...

logs: Add partition to warning upon log Truncation

---

parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/internal/BrokerPollSystem.java

From PR - pause and resume Poller #198 
Poller will pause naturally via back pressure if the controller is paused.
See comment where removal was discussed, but was some fragments were left in:
https://github.com/confluentinc/parallel-consumer/pull/198#discussion_r815775909

minor: Remove dangling API methods which were kept by accident

---

CHANGELOG.adoc
README.adoc
parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/state/PartitionState.java
parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/state/ProcessingShard.java
parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/state/WorkContainer.java

> Under unrealistically high load with no-op processing, broker poller unblocking a partition could cause ProcessingShard to skip forward in its entries and take work out of order.
> Was discovered when fixing a synthetic high performance benchmark, after an O(n) algo was fixed to O(1), creating the state for the race condition to appear. Probably could not happen without the fix, as it's related to the performance of certain parts of the system.
> This sort of issue won't be possible once the new IPC system is merged and Thread contracts established. 
Related:
- #530 
- #325 
- #270

fix: After new performance fix PR#530 merges - corner case could cause out of order processing

---

CHANGELOG.adoc
README.adoc
parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/offsets/OffsetRunLength.java
parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/state/PartitionState.java
parallel-consumer-core/src/test/java/io/confluent/parallelconsumer/offsets/OffsetEncodingTests.java

When offset data is serialized using RunLength encoder - and base offset to commit is same as the next expected offset - 1 (or lower) - basically there is no extended metadata to encode - could be caused by slow processing (slower than consumption) or on rebalance etc.
When that data is subsequently decoded - the HighestOffset is returned as 0 - that causes the warning about state truncation to be shown and the bootstrap state truncation logic to be invoked.
This fix addresses the decoding side - initializing the HighestOffset = baseOffset-1 - same as bitset decoder, but potentially we could detect and skip encoding of metadata in those scenarios - need to dig deeper and can be done as follow up.
Related issue #546

fix: runlength decoding after no-progress commit

---

CHANGELOG.adoc
README.adoc
parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/internal/AbstractParallelEoSStreamProcessor.java
parallel-consumer-core/src/test-integration/java/io/confluent/parallelconsumer/integrationTests/RebalanceEoSDeadlockTest.java

Fixes https://github.com/confluentinc/parallel-consumer/issues/541

Fix deadlock between pc-control and pc-broker-poll threads where partitions are revoked 

---

parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/internal/AbstractParallelEoSStreamProcessor.java
parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/state/ProcessingShard.java
parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/state/WorkManager.java

The "Can't take as work ..." trace message is created even when trace logging is not enabled. In our profiler we saw that this generates a significant amount of garbage. This PR only generates the message if trace logging is enabled.

Do not create trace log message when trace logging is not enabled

---

parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/ParallelConsumerOptions.java
parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/offsets/EncodedOffsetPair.java
parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/offsets/OffsetMapCodecManager.java
parallel-consumer-core/src/test/java/io/confluent/parallelconsumer/offsets/WorkManagerOffsetMapCodecManagerTest.java

Improves: https://github.com/confluentinc/parallel-consumer/issues/326 
Adds an option to pass an invalid offset metadata error policy in case of accidentally or deliberately reusing a Kafka Streams consumer group. The default policy is to fail and stop the execution.

improves: Error in onPartitionsAssigned in parallel consumer

---

README.adoc
parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/metrics/PCMetrics.java
parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/offsets/OffsetEncoder.java
parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/state/RemovedPartitionState.java
parallel-consumer-core/src/test/java/io/confluent/parallelconsumer/ParallelEoSStreamProcessorTestBase.java
parallel-consumer-examples/parallel-consumer-example-metrics/src/main/java/io/confluent/parallelconsumer/examples/metrics/CoreApp.java

minor fixes - fix for metrics example in readme and couple of missed license header updates.

fix: example in readme, license headers

---

CHANGELOG.adoc
README.adoc
parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/ParallelConsumerOptions.java
parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/internal/AbstractParallelEoSStreamProcessor.java
parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/internal/BrokerPollSystem.java
parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/internal/DrainingCloseable.java
parallel-consumer-core/src/test-integration/java/io/confluent/parallelconsumer/integrationTests/TransactionTimeoutsTest.java
parallel-consumer-core/src/test/java/io/confluent/parallelconsumer/ParallelEoSStreamProcessorTest.java
parallel-consumer-core/src/test/java/io/confluent/parallelconsumer/internal/ProducerManagerTest.java

Handle close dont drain mode gracefully.
Addresses issue - #559 
Added ParallelConsumerOptions shutdownTimeout - shutdown timeout is used during closeDontDrain shutdown - but because that is invoked on error as well - this option allows to set the timeout during PC creation.
Added ParallelConsumerOptions drainTimeout - to allow to specify time bound for draining the queues separately from shutdown timeout.

PL-176 handle close dont drain mode gracefully

---

CHANGELOG.adoc
README.adoc
parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/state/PartitionStateManager.java
parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/state/ProcessingShard.java
parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/state/ShardManager.java

Description...
This is the fix for https://github.com/confluentinc/parallel-consumer/issues/606
The issue happens when rebalancing and partitions got re-assigned:
1. The `workcontainer` will be marked as stale container since its epoch is mismatch between `partitionsAssignmentEpoch` of `PartitionState` and `epoch` from `WorkContainer`
https://github.com/confluentinc/parallel-consumer/blob/master/parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/state/PartitionState.java#L655
2. `inFlight` of `WorkContainer` will be stay false since they will be filtered to be selected in `runUserFunction` in `AbstractParallelEoSStreamProcessor`
https://github.com/confluentinc/parallel-consumer/blob/master/parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/internal/AbstractP …

fix : for issue 606 : exclude stale containers from counting and add remove add remove staled work containers function in ProcessingShard

---

parallel-consumer-core/pom.xml
pom.xml

Remove micrometer-atlas dependency. 
It is causing issues in Spring as it autoconfigures use of Atlas registry which may not be present and causes attempts to send metrics that fail with warnings.
It was added by mistake and not actually needed.

PL-464 remove micrometer-atlas dependency

---

parallel-consumer-core/src/main/java/io/confluent/csid/utils/SupplierUtils.java
parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/internal/AbstractParallelEoSStreamProcessor.java
parallel-consumer-core/src/test/java/io/confluent/csid/utils/SupplierUtilsTest.java

Change `Suppliers` utils class to `SupplierUtils` since all other utils ends with xxxUtils postfix.
https://github.com/confluentinc/parallel-consumer/tree/master/parallel-consumer-core/src/main/java/io/confluent/csid/utils

minor: Change Supplier -> SupplierUtils for consistency

---

README.adoc
src/docs/README_TEMPLATE.adoc

In ReadMe. it introduce the metric function.
```
var options = ParallelConsumerOptions.<String, String>builder()
.ordering(ParallelConsumerOptions.ProcessingOrder.KEY)
.maxConcurrency(1000)
.consumer(kafkaConsumer)
.meterRegistry(meterRegistry)                     //(1)
.metricsTags(Tags.of(Tag.of("instance", "pc1")))    //(2)
.build();
......
kafkaClientMetrics = new KafkaClientMetrics(kafkaConsumer); //(3)
kafkaClientMetrics.bindTo(meterRegistry);                 //(4)
```
with gloss
```
1. Optional - Kafka Consumer Micrometer metrics object created for Kafka Consumer that is later used for Parallel Consumer.
2. Optional - Kafka Consumer Micrometer metrics are bound to Meter Registry.
3. Meter Registry is set through ParallelConsumerOptions.builder(), if not specified - will default to …
```

fix readme doc

---

CHANGELOG.adoc
README.adoc
parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/state/ShardKey.java
parallel-consumer-core/src/test/java/io/confluent/parallelconsumer/state/ShardKeyTest.java

Fixed key equality comparison - use deep equality / hash code for Object and primitive arrays.
Resolves #579

PL-354 - fix key equality

---

CHANGELOG.adoc
parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/internal/AbstractParallelEoSStreamProcessor.java
parallel-consumer-core/src/test/java/io/confluent/parallelconsumer/AbstractParallelEoSStreamProcessorConfigurationTest.java
parallel-consumer-core/src/test/java/io/confluent/parallelconsumer/ParallelEoSStreamProcessorNonRunningTest.java
parallel-consumer-core/src/test/java/io/confluent/parallelconsumer/internal/TestParallelEoSStreamProcessor.java

Addresses a bug identified in a slack thread (https://confluentcommunity.slack.com/archives/C051K2TJLPQ/p1699018828805729) which causes the inflight queue to scale by `batchSize * batchSize * maxConcurrency * dynamicLoadFactor` rather than `batchSize * maxConcurrency * dynamicLoadFactor`

Remove duplicated batchSize factor from target load; add a test case

---

CHANGELOG.adoc
README.adoc
parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/internal/AbstractParallelEoSStreamProcessor.java
parallel-consumer-core/src/test-integration/java/io/confluent/parallelconsumer/integrationTests/BrokerIntegrationTest.java
parallel-consumer-core/src/test-integration/java/io/confluent/parallelconsumer/integrationTests/RebalanceTest.java

Fix synchronisation logic between transactional producer commit and partition revocation commit
* Fixes https://github.com/confluentinc/parallel-consumer/issues/637

Fix synchronisation logic between commits

---

parallel-consumer-core/pom.xml
parallel-consumer-examples/parallel-consumer-example-core/pom.xml
parallel-consumer-examples/parallel-consumer-example-metrics/pom.xml
pom.xml

Http scheme is used in couple of example sub-module POM files for repository location - updated to HTTPS.
See #675

use https for repositories

---

CHANGELOG.adoc
README.adoc
parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/ParallelConsumerOptions.java
parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/internal/DynamicLoadFactor.java
parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/internal/PCModule.java
parallel-consumer-core/src/test-integration/java/io/confluent/parallelconsumer/integrationTests/PartitionOrderProcessingTest.java
parallel-consumer-core/src/test/java/io/confluent/parallelconsumer/internal/LimitedDynamicExtraLoadFactor.java
src/docs/README_TEMPLATE.adoc

Make PC message buffer size configurable.
Two configuration options added - specifying message buffer size (which will calculate loading factor and set loading factor to static value) and configurable initial and max loading factors.
* messageBufferSize - takes precedence if specified over load factor options - sets buffer size to approximately specified value by setting load factor to static value calculated as `ceiling ( messageBufferSize / maxConcurrency*batchSize) `
* initialLoadFactor - (default 2) - overrides starting load factor value
* maximumLoadFactor - (default 100) - overrides maximum load factor value
Readme updated to add consideration to tune fetch and buffer size in Partition ordering mode as buffer size can be small by default leading to uneven load per partition and …

Make PC message buffer size configurable

---

CHANGELOG.adoc
parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/RecordContext.java

`RecordContext` now exposes `lastFailurReason`  from `WorkContainer`, this is useful for diagnostic and problem analysis purposes.

GH-725: RecordContext should provide access to lastFailureReason

---

README.adoc
parallel-consumer-examples/parallel-consumer-example-core/src/main/java/io/confluent/parallelconsumer/examples/core/CoreApp.java

Fixed the example code for skipping records to work properly. Previously, the example code did not work correctly because retriesCount was constantly 0.

Fix the example code for skipping records to work properly

---

service.yml

Enable semaphore as part of migrating builds from jenkins to semaphoreCI

Enable semaphore as part of migrating builds from jenkins to semaphoreCI

---

CHANGELOG.adoc
README.adoc
parallel-consumer-reactor/src/main/java/io/confluent/parallelconsumer/reactor/ReactorProcessor.java

* Support for PCRetriableException in ReactorProcessor.
* Error handling moved to subscribe param to avoid onErrorDropped.

fix: Support for PCRetriableException in ReactorProcessor (#733)

---

CHANGELOG.adoc
README.adoc
parallel-consumer-core/src/test/java/io/confluent/csid/utils/LongPollingMockConsumer.java
pom.xml

Rebalance listeners are invoked by `MockConsumer` since Kafka 3.6.0 (https://github.com/apache/kafka/compare/3.5...3.6#diff-0ebcab2d2727abe3f0f1e3a94321b068ef2478911a33861d072a7a2ecbb1cf1f). Doing it manually is no longer necessary.
The redundant listener invocation caused test failures, for example `PCMetricsTest` (see https://github.com/confluentinc/parallel-consumer/pull/762#issuecomment-2108553270).
Refer to https://github.com/confluentinc/parallel-consumer/pull/762#issuecomment-2110677240 for more details.

Fix redundant rebalance callback in `LongPollingMockConsumer` for Kafka >= 3.6

---

parallel-consumer-examples/parallel-consumer-example-reactor/src/main/java/io/confluent/parallelconsumer/examples/reactor/ReactorApp.java
parallel-consumer-examples/parallel-consumer-example-reactor/src/test/java/io/confluent/parallelconsumer/examples/reactor/ReactorAppTest.java

Remove redundant line in the example

Remove redundant line in the React example

---

CHANGELOG.adoc
parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/internal/AbstractParallelEoSStreamProcessor.java
parallel-consumer-core/src/test/java/io/confluent/parallelconsumer/AbstractParallelEoSStreamProcessorConfigurationTest.java
parallel-consumer-core/src/test/java/io/confluent/parallelconsumer/internal/TestParallelEoSStreamProcessor.java

Description...
in previous logic we need two passes to get the normal containers and put stale containers into mailbox queue.
But now we only need one pass, therefore when the traffic is huge, there will be performance gain.

stale containers exclusion and handling improvement

---

CHANGELOG.adoc
README.adoc

Change version in changelog / readme for 0.5.3.0 release.
One of main dependencies (Kafka-clients) updated to 3.7 - it has significant changes, therefore releasing as 0.5.3.0 instead of 0.5.2.9.

change version in changelog / readme for 0.5.3.0 release

---

.semaphore/publish_to_maven.yml
parallel-consumer-core/pom.xml
parallel-consumer-examples/parallel-consumer-example-core/pom.xml
parallel-consumer-examples/parallel-consumer-example-metrics/pom.xml
parallel-consumer-examples/parallel-consumer-example-reactor/pom.xml
parallel-consumer-examples/parallel-consumer-example-streams/pom.xml
parallel-consumer-examples/parallel-consumer-example-vertx/pom.xml
parallel-consumer-examples/pom.xml
parallel-consumer-reactor/pom.xml
parallel-consumer-vertx/pom.xml
pom.xml

Revert release prep.
Update python script path in publish step.

Revert release update script path

---

.semaphore/semaphore.yml

Publish auto promote triggers on tag rename (soft delete) - disable for now

remove publish auto-promotion

---

parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/internal/AbstractParallelEoSStreamProcessor.java

Ensure that `doClose()` completes and successfully transitions the StreamProcessor to CLOSED state. Unhandled exception during `doClose()` results in a degraded StreamProcessor with terminated control loop but stuck in RUNNING state. 
This is critical to support accurate external monitoring of `isClosedOrFailed()` by user code.
see https://github.com/confluentinc/parallel-consumer/issues/809

fix: safely completing doClose()

---

.semaphore/publish_to_maven.yml
parallel-consumer-core/pom.xml
parallel-consumer-examples/parallel-consumer-example-core/pom.xml
parallel-consumer-examples/parallel-consumer-example-metrics/pom.xml
parallel-consumer-examples/parallel-consumer-example-reactor/pom.xml
parallel-consumer-examples/parallel-consumer-example-streams/pom.xml
parallel-consumer-examples/parallel-consumer-example-vertx/pom.xml
parallel-consumer-examples/pom.xml
parallel-consumer-reactor/pom.xml
parallel-consumer-vertx/pom.xml
pom.xml

Sonatype (OSSRH) / Repo1 auth logic has changed and requires use of user tokens instead of just user / password pair.
Reverting the release (as this is only used when pushing release to repo1) and updating semaphore file to use secrets with token info.

Revert release 0.5.3.1 and update Sonatype creds to use token

---

CHANGELOG.adoc
parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/state/PartitionState.java
parallel-consumer-core/src/test/java/io/confluent/parallelconsumer/ParallelEoSSStreamProcessorRebalancedTest.java

Description...
fix for #826.
Explanation:
The root cause is that :
1. currently the offset to be committed is according to `offsetHighestSeen `, but this variable is updated as soon as it is polled from kafka and not processed yet.
2. The committer is independent of the message processing since it is periodic committer within `BrokerPollSystem`
3. right before the container is ready to be processed, the partition revoked.
4. And the container is regarded as stale but this is correct behavior but the problem is that the offset is committed, the new consumer will skip this record.
The issue is rare because it has to met with following conditions:
```
1. before the work container is executed (selected ready to be run), the partition revoked (close / rebalancing)
2. there is commit happen, …
```

fix for message loss for issue 826

---

CHANGELOG.adoc
README.adoc
parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/state/ProcessingShard.java
parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/state/RetryQueue.java
parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/state/ShardManager.java
parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/state/WorkContainer.java
parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/state/WorkManager.java
parallel-consumer-core/src/test-integration/java/io/confluent/parallelconsumer/integrationTests/RetriesTest.java
parallel-consumer-core/src/test-integration/java/io/confluent/parallelconsumer/integrationTests/utils/KafkaClientUtils.java
parallel-consumer-core/src/test/java/io/confluent/parallelconsumer/state/ShardManagerTest.java
parallel-consumer-core/src/test/java/io/confluent/parallelconsumer/truth/ConsumerSubject.java

Fixes #832 #817 
RetryQueue implementation is incorrect due to difference in WorkContainer equals (which is done by topic, partition and offset) and ordering / comparator used for NavigatableSet.
NavigatableSet (or more broadly - standard SortedSet implementations in Java) - use comparator for uniqueness checks instead of equals - and sorting is done taking retryDueAt into account - hence work containers with same topic, partition and offset but differing retryDueAt values are treated as not equal leading to "duplicates" and unbounded retry queue growth on looping retries.
Implementation is rewritten using double Map approach - HashMap for uniqueness checks and TreeMap for sorting.
ReadWrite lock used for access synchronisation - while allowing for concurrent reads.
There is still slight …

Fix retry queue implementation to prevent unbounded growth

---

CHANGELOG.adoc
README.adoc
parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/internal/AbstractParallelEoSStreamProcessor.java
parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/internal/BrokerPollSystem.java
parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/state/WorkManager.java
parallel-consumer-core/src/test-integration/java/io/confluent/parallelconsumer/integrationTests/BrokerPollerBackpressureTest.java
parallel-consumer-core/src/test-integration/java/io/confluent/parallelconsumer/integrationTests/utils/KafkaClientUtils.java

When determination is done if consumer should be paused - the messages in processing queues / worker thread pool queue and threads should be taken into account along with messages in the shards.
Note that pausing can happen sooner now in certain situations - as inflight / queued in thread pool messages were not counted for buffer size previously but now they are counted in.

Fix buffer size include in flight messages in backpressure calculation logic

---

CHANGELOG.adoc
README.adoc
parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/ParallelEoSStreamProcessor.java
parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/internal/AbstractParallelEoSStreamProcessor.java
parallel-consumer-core/src/test/java/io/confluent/parallelconsumer/ParallelEoSStreamProcessorTest.java

Closes #830 
Problem
In transactional mode, when ParallelConsumer encounters an InvalidPidMapping exception, it retries records indefinitely leading to same exception.
Proposed Solution
Parallel Consumer should exit when encoutering InvalidPidMapping.

fixes #830: Close PC when InvalidPidMappingException

---

CHANGELOG.adoc
parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/internal/AbstractParallelEoSStreamProcessor.java

[KAFKA-17060](https://issues.apache.org/jira/browse/KAFKA-17060) broke the retrieval of autocommit enabled in
AbstractParallelEoSStreamProcessor#getAutoCommitEnabled.
Relates to #840

Support Kafka-clients 3.9.0

---

.semaphore/publish_to_maven.yml
.semaphore/update_maven_settings.py
parallel-consumer-core/src/test-integration/java/io/confluent/parallelconsumer/integrationTests/BrokerIntegrationTest.java
pom.xml

This pull request updates the Maven publishing workflow to use Sonatype Central instead of OSSRH, aligning credentials and plugin configuration across the CI pipeline and build files. The changes ensure that publishing uses the new Sonatype Central infrastructure and credentials, and replace the legacy Nexus Staging plugin with the new Central Publishing plugin.
**CI/CD Pipeline and Credential Updates:**
* Updated environment variable names and values in `.semaphore/publish_to_maven.yml` to use `CENTRAL_TOKEN_USERNAME`, `CENTRAL_TOKEN_PASSWORD`, and `central` instead of OSSRH-related variables and server ID.
* Modified `.semaphore/update_maven_settings.py` to retrieve Sonatype Central credentials from the new environment variables.
**Maven Build and Publishing Configuration:**
* Removed …

Migrate ossrh to maven plugin

---

parallel-consumer-core/pom.xml
parallel-consumer-examples/parallel-consumer-example-core/pom.xml
parallel-consumer-examples/parallel-consumer-example-metrics/pom.xml
parallel-consumer-examples/parallel-consumer-example-reactor/pom.xml
parallel-consumer-examples/parallel-consumer-example-streams/pom.xml
parallel-consumer-examples/parallel-consumer-example-vertx/pom.xml
parallel-consumer-examples/pom.xml
parallel-consumer-reactor/pom.xml
parallel-consumer-vertx/pom.xml

CI/CD failed due to license format header not being up-to-date 
```
Warning: JAVA_HOME environment variable is not set.00:00
[ERROR] Failed to execute goal com.mycila:license-maven-plugin:5.0.0:check (default) on project parallel-consumer-parent: Some files do not have the expected license header. Run license:format to update them. -> [Help 1]01:09
[ERROR] 01:09
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.01:09
[ERROR] Re-run Maven using the -X switch to enable full debug logging.01:09
[ERROR] 01:09
[ERROR] For more information about the errors and possible solutions, please read the following articles:01:09
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

Fix license format
